class MockData{
  static const String jsonMock = '''
  {
  "total_count": 573491,
  "incomplete_results": false,
  "items": [
    {
      "id": 31792824,
      "node_id": "MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==",
      "name": "flutter",
      "full_name": "flutter/flutter",
      "private": false,
      "owner": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/flutter/flutter",
      "description": "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/flutter",
      "forks_url": "https://api.github.com/repos/flutter/flutter/forks",
      "keys_url": "https://api.github.com/repos/flutter/flutter/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/flutter/flutter/teams",
      "hooks_url": "https://api.github.com/repos/flutter/flutter/hooks",
      "issue_events_url": "https://api.github.com/repos/flutter/flutter/issues/events{/number}",
      "events_url": "https://api.github.com/repos/flutter/flutter/events",
      "assignees_url": "https://api.github.com/repos/flutter/flutter/assignees{/user}",
      "branches_url": "https://api.github.com/repos/flutter/flutter/branches{/branch}",
      "tags_url": "https://api.github.com/repos/flutter/flutter/tags",
      "blobs_url": "https://api.github.com/repos/flutter/flutter/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/flutter/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/flutter/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/flutter/flutter/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/flutter/flutter/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/flutter/flutter/languages",
      "stargazers_url": "https://api.github.com/repos/flutter/flutter/stargazers",
      "contributors_url": "https://api.github.com/repos/flutter/flutter/contributors",
      "subscribers_url": "https://api.github.com/repos/flutter/flutter/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/flutter/subscription",
      "commits_url": "https://api.github.com/repos/flutter/flutter/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/flutter/flutter/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/flutter/flutter/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/flutter/flutter/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/flutter/flutter/contents/{+path}",
      "compare_url": "https://api.github.com/repos/flutter/flutter/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/flutter/flutter/merges",
      "archive_url": "https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/flutter/flutter/downloads",
      "issues_url": "https://api.github.com/repos/flutter/flutter/issues{/number}",
      "pulls_url": "https://api.github.com/repos/flutter/flutter/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/flutter/flutter/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/flutter/flutter/labels{/name}",
      "releases_url": "https://api.github.com/repos/flutter/flutter/releases{/id}",
      "deployments_url": "https://api.github.com/repos/flutter/flutter/deployments",
      "created_at": "2015-03-06T22:54:58Z",
      "updated_at": "2023-08-29T01:47:04Z",
      "pushed_at": "2023-08-29T01:32:04Z",
      "git_url": "git://github.com/flutter/flutter.git",
      "ssh_url": "git@github.com:flutter/flutter.git",
      "clone_url": "https://github.com/flutter/flutter.git",
      "svn_url": "https://github.com/flutter/flutter",
      "homepage": "https://flutter.dev",
      "size": 269758,
      "stargazers_count": 156251,
      "watchers_count": 156251,
      "language": "Dart",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 25942,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 11654,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "android",
        "app-framework",
        "cross-platform",
        "dart",
        "dart-platform",
        "desktop",
        "flutter",
        "flutter-package",
        "fuchsia",
        "ios",
        "linux-desktop",
        "macos",
        "material-design",
        "mobile",
        "mobile-development",
        "skia",
        "web",
        "web-framework",
        "windows"
      ],
      "visibility": "public",
      "forks": 25942,
      "open_issues": 11654,
      "watchers": 156251,
      "default_branch": "master",
      "score": 1.0
    }
    {
      "id": 431098851,
      "node_id": "R_kgDOGbIL4w",
      "name": "ddd-framework",
      "full_name": "lml200701158/ddd-framework",
      "private": false,
      "owner": {
        "login": "lml200701158",
        "id": 14948847,
        "node_id": "MDQ6VXNlcjE0OTQ4ODQ3",
        "avatar_url": "https://avatars.githubusercontent.com/u/14948847?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lml200701158",
        "html_url": "https://github.com/lml200701158",
        "followers_url": "https://api.github.com/users/lml200701158/followers",
        "following_url": "https://api.github.com/users/lml200701158/following{/other_user}",
        "gists_url": "https://api.github.com/users/lml200701158/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lml200701158/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lml200701158/subscriptions",
        "organizations_url": "https://api.github.com/users/lml200701158/orgs",
        "repos_url": "https://api.github.com/users/lml200701158/repos",
        "events_url": "https://api.github.com/users/lml200701158/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lml200701158/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/lml200701158/ddd-framework",
      "description": "DDD框架",
      "fork": false,
      "url": "https://api.github.com/repos/lml200701158/ddd-framework",
      "forks_url": "https://api.github.com/repos/lml200701158/ddd-framework/forks",
      "keys_url": "https://api.github.com/repos/lml200701158/ddd-framework/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/lml200701158/ddd-framework/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/lml200701158/ddd-framework/teams",
      "hooks_url": "https://api.github.com/repos/lml200701158/ddd-framework/hooks",
      "issue_events_url": "https://api.github.com/repos/lml200701158/ddd-framework/issues/events{/number}",
      "events_url": "https://api.github.com/repos/lml200701158/ddd-framework/events",
      "assignees_url": "https://api.github.com/repos/lml200701158/ddd-framework/assignees{/user}",
      "branches_url": "https://api.github.com/repos/lml200701158/ddd-framework/branches{/branch}",
      "tags_url": "https://api.github.com/repos/lml200701158/ddd-framework/tags",
      "blobs_url": "https://api.github.com/repos/lml200701158/ddd-framework/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/lml200701158/ddd-framework/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/lml200701158/ddd-framework/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/lml200701158/ddd-framework/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/lml200701158/ddd-framework/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/lml200701158/ddd-framework/languages",
      "stargazers_url": "https://api.github.com/repos/lml200701158/ddd-framework/stargazers",
      "contributors_url": "https://api.github.com/repos/lml200701158/ddd-framework/contributors",
      "subscribers_url": "https://api.github.com/repos/lml200701158/ddd-framework/subscribers",
      "subscription_url": "https://api.github.com/repos/lml200701158/ddd-framework/subscription",
      "commits_url": "https://api.github.com/repos/lml200701158/ddd-framework/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/lml200701158/ddd-framework/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/lml200701158/ddd-framework/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/lml200701158/ddd-framework/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/lml200701158/ddd-framework/contents/{+path}",
      "compare_url": "https://api.github.com/repos/lml200701158/ddd-framework/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/lml200701158/ddd-framework/merges",
      "archive_url": "https://api.github.com/repos/lml200701158/ddd-framework/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/lml200701158/ddd-framework/downloads",
      "issues_url": "https://api.github.com/repos/lml200701158/ddd-framework/issues{/number}",
      "pulls_url": "https://api.github.com/repos/lml200701158/ddd-framework/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/lml200701158/ddd-framework/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/lml200701158/ddd-framework/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/lml200701158/ddd-framework/labels{/name}",
      "releases_url": "https://api.github.com/repos/lml200701158/ddd-framework/releases{/id}",
      "deployments_url": "https://api.github.com/repos/lml200701158/ddd-framework/deployments",
      "created_at": "2021-11-23T12:51:03Z",
      "updated_at": "2023-08-26T06:36:48Z",
      "pushed_at": "2023-04-20T23:36:57Z",
      "git_url": "git://github.com/lml200701158/ddd-framework.git",
      "ssh_url": "git@github.com:lml200701158/ddd-framework.git",
      "clone_url": "https://github.com/lml200701158/ddd-framework.git",
      "svn_url": "https://github.com/lml200701158/ddd-framework",
      "homepage": null,
      "size": 38,
      "stargazers_count": 170,
      "watchers_count": 170,
      "language": "Java",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 122,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 6,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 122,
      "open_issues": 6,
      "watchers": 170,
      "default_branch": "master",
      "score": 1.0
    },
  ]
}
  ''';
  static const String noJsonData = '''
  {
  "total_count": 0,
  "items": []
}
  ''';
}